general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/kieran/Pictures/wallpaper3.jpg
    blur_passes = 2
}

input-field {
    monitor =
    size = 260, 48
    position = 0, -40
    halign = center
    valign = center
}
